// ==========================================
// NETFLIX CLONE - CONFIGURATION
// ==========================================

const CONFIG = {
    content: {
        trending: [
            {
                id: 1,
                title: 'Wednesday',
                image: 'https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
                trailer: 'Di310WS8zLk',
                year: 2022,
                rating: 'TV-14',
                duration: '1 Season',
                match: 97,
                description: 'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree at Nevermore Academy.',
                cast: 'Jenna Ortega, Gwendoline Christie, Riki Lindhome',
                genres: 'Comedy, Mystery, Supernatural',
                tags: 'Dark, Quirky, Teen',
                badge: 'new'
            },
            {
                id: 2,
                title: 'Squid Game',
                image: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
                trailer: 'oqxAJKy0ii4',
                year: 2021,
                rating: 'TV-MA',
                duration: '2 Seasons',
                match: 98,
                description: 'Hundreds of cash-strapped players compete in deadly children\'s games for a life-changing prize.',
                cast: 'Lee Jung-jae, Park Hae-soo, Wi Ha-jun',
                genres: 'Thriller, Drama, Action',
                tags: 'Dark, Suspenseful, Violent'
            },
            {
                id: 3,
                title: 'The Witcher',
                image: 'https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg',
                trailer: 'ndl1W4ltcmg',
                year: 2019,
                rating: 'TV-MA',
                duration: '3 Seasons',
                match: 95,
                description: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a cruel world.',
                cast: 'Henry Cavill, Anya Chalotra, Freya Allan',
                genres: 'Fantasy, Adventure, Action',
                tags: 'Dark, Epic, Violent'
            },
            {
                id: 4,
                title: 'Money Heist',
                image: 'https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg',
                trailer: '_InqKYnsjec',
                year: 2017,
                rating: 'TV-MA',
                duration: '5 Seasons',
                match: 96,
                description: 'Eight thieves take hostages in the Royal Mint of Spain while a mastermind manipulates the police.',
                cast: 'Álvaro Morte, Úrsula Corberó, Itziar Ituño',
                genres: 'Crime, Thriller, Action',
                tags: 'Heist, Suspenseful'
            },
            {
                id: 5,
                title: 'The Crown',
                image: 'https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg',
                trailer: 'JWtnJjn6ng0',
                year: 2016,
                rating: 'TV-MA',
                duration: '6 Seasons',
                match: 92,
                description: 'Political rivalries and romance during Queen Elizabeth II\'s reign.',
                cast: 'Imelda Staunton, Jonathan Pryce, Lesley Manville',
                genres: 'Drama, Biography, History',
                tags: 'Period Piece, Royal'
            },
            {
                id: 6,
                title: 'Bridgerton',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM9rPXCc98IS3_onlQTgQQxZISw9U_41ToW8Nricr0P8NLPn6PATvF-cqUKDeFk4bfXTCUcA&s=10',
                trailer: 'gpv7ayf_tyE',
                year: 2020,
                rating: 'TV-MA',
                duration: '3 Seasons',
                match: 94,
                description: 'The Bridgerton family navigates London\'s high society in search of love.',
                cast: 'Nicola Coughlan, Luke Newton, Phoebe Dynevor',
                genres: 'Romance, Drama, Period',
                tags: 'Romantic, Steamy'
            },
            {
                id: 7,
                title: 'Ginny & Georgia',
                image: 'https://m.media-amazon.com/images/M/MV5BNGY4NjYzYTYtMDhjYy00MmQ2LTkwNDktNzUxMGNkMDI5MmZhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: 'eC-tFJEkLVE',
                year: 2021,
                rating: 'TV-14',
                duration: '2 Seasons',
                match: 86,
                description: 'Georgia Miller and her daughter Ginny start over in a New England town.',
                cast: 'Antonia Gentry, Brianne Howey, Felix Mallard',
                genres: 'Drama, Comedy',
                tags: 'Teen, Coming-of-Age'
            },
            {
                id: 8,
                title: 'The Diplomat',
                image: 'https://m.media-amazon.com/images/M/MV5BNjNhODY5OWEtZjMxNy00NzFhLWIzOTQtZTNmYjUwOGRiMzYwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: 'TfLvWu7llQA',
                year: 2023,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 90,
                description: 'Career diplomat Kate Wyler lands a high-profile job amid an international crisis.',
                cast: 'Keri Russell, Rufus Sewell, Ali Ahn',
                genres: 'Thriller, Drama',
                tags: 'Political, Suspenseful'
            },
            {
                id: 9,
                title: 'You',
                image: 'https://image.tmdb.org/t/p/w500/7bEYwjUvlJW7GerM8GYmqwl4oS3.jpg',
                trailer: 'bR_1xHgVAAQ',
                year: 2018,
                rating: 'TV-MA',
                duration: '4 Seasons',
                match: 93,
                description: 'A dangerously charming man goes to extreme measures to insert himself into the lives of those he is obsessed with.',
                cast: 'Penn Badgley, Elizabeth Lail, Ambyr Childers',
                genres: 'Thriller, Drama, Crime',
                tags: 'Dark, Psychological'
            },
            {
                id: 10,
                title: 'Firefly Lane',
                image: 'https://m.media-amazon.com/images/M/MV5BZDY3OWExOWEtMjI1Mi00NzQzLWE5ZTktZDM2Nzc4MjU3NjcwXkEyXkFqcGc@._V1_.jpg',
                trailer: 'LppP2h0qxlI',
                year: 2021,
                rating: 'TV-14',
                duration: '2 Seasons',
                match: 87,
                description: 'Best friends Kate and Tully weather life\'s storms over decades.',
                cast: 'Katherine Heigl, Sarah Chalke, Ali Skovbye',
                genres: 'Drama, Comedy',
                tags: 'Emotional, Nostalgic'
            },
            {
                id: 11,
                title: 'Sweet Magnolias',
                image: 'https://m.media-amazon.com/images/M/MV5BNDRmZWEyY2MtMmM5Mi00N2UwLWE2MzQtZGU0OWJhY2IxNThmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: '7K-fXdMxIJQ',
                year: 2020,
                rating: 'TV-14',
                duration: '3 Seasons',
                match: 85,
                description: 'Lifelong friends juggle relationships, family, and careers in Serenity.',
                cast: 'JoAnna Garcia Swisher, Brooke Elliott, Heather Headley',
                genres: 'Drama',
                tags: 'Friendship, Southern'
            },
            {
                id: 12,
                title: 'Chilling Adventures of Sabrina',
                image: 'https://image.tmdb.org/t/p/w500/yxMpoHO0CXP5o9gB7IfsciilQS4.jpg',
                trailer: 'LgHnXpzKKVw',
                year: 2018,
                rating: 'TV-14',
                duration: '4 Seasons',
                match: 88,
                description: 'Half-witch Sabrina navigates mortal life and her family\'s dark legacy.',
                cast: 'Kiernan Shipka, Ross Lynch, Lucy Davis',
                genres: 'Fantasy, Horror, Drama',
                tags: 'Dark, Witches'
            }
        ],

        popular: [
            {
                id: 21,
                title: 'Stranger Things',
                image: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
                trailer: 'OsqUh1p1Ock',
                year: 2016,
                rating: 'TV-14',
                duration: '4 Seasons',
                match: 98,
                description: 'A small town uncovers supernatural mysteries when a boy disappears.',
                cast: 'Millie Bobby Brown, Finn Wolfhard, Winona Ryder',
                genres: 'Sci-Fi, Horror, Drama',
                tags: 'Nostalgic, Scary, 80s'
            },
            {
                id: 22,
                title: 'Breaking Bad',
                image: 'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
                trailer: 'HhesaQXLuRY',
                year: 2008,
                rating: 'TV-MA',
                duration: '5 Seasons',
                match: 99,
                description: 'A chemistry teacher turns to making meth to secure his family\'s future.',
                cast: 'Bryan Cranston, Aaron Paul, Anna Gunn',
                genres: 'Crime, Drama, Thriller',
                tags: 'Dark, Gritty, Intense'
            },
            {
                id: 23,
                title: 'Dark',
                image: 'https://image.tmdb.org/t/p/w500/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
                trailer: 'rrwycJ08PSA',
                year: 2017,
                rating: 'TV-MA',
                duration: '3 Seasons',
                match: 96,
                description: 'A German town\'s secrets unravel after children disappear.',
                cast: 'Louis Hofmann, Karoline Eichhorn, Lisa Vicari',
                genres: 'Thriller, Sci-Fi, Mystery',
                tags: 'Mind-Bending, Dark'
            },
            {
                id: 24,
                title: 'Peaky Blinders',
                image: 'https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg',
                trailer: 'oVzVdvGIC7U',
                year: 2013,
                rating: 'TV-MA',
                duration: '6 Seasons',
                match: 95,
                description: 'A gangster family in 1919 Birmingham sews razor blades into their caps.',
                cast: 'Cillian Murphy, Paul Anderson, Sophie Rundle',
                genres: 'Crime, Drama, Period',
                tags: 'Gritty, Stylish, Violent'
            },
            {
                id: 25,
                title: 'Ozark',
                image: 'https://m.media-amazon.com/images/M/MV5BZDk1ZTdjOWItNTJmYS00MGIzLThmY2ItZWNiOGY5MzJlNTA5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: '5hAXVqrljbs',
                year: 2017,
                rating: 'TV-MA',
                duration: '4 Seasons',
                match: 94,
                description: 'A financial adviser launders money in the Ozarks to appease a drug boss.',
                cast: 'Jason Bateman, Laura Linney, Sofia Hublitz',
                genres: 'Crime, Drama, Thriller',
                tags: 'Dark, Suspenseful'
            },
            {
                id: 26,
                title: 'The Queen\'s Gambit',
                image: 'https://image.tmdb.org/t/p/w500/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg',
                trailer: 'CDrieqwSdgI',
                year: 2020,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 97,
                description: 'A chess prodigy battles addiction while chasing greatness.',
                cast: 'Anya Taylor-Joy, Chloe Pirrie, Bill Camp',
                genres: 'Drama, Period',
                tags: 'Inspiring, Period Piece'
            },
            {
                id: 27,
                title: 'Mindhunter',
                image: 'https://m.media-amazon.com/images/M/MV5BYTk4NDA4MGMtNjliOC00MjExLWI1YzctOTc4NWIxM2I1YjM5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: 'aLEVRYFxQhc',
                year: 2017,
                rating: 'TV-MA',
                duration: '2 Seasons',
                match: 91,
                description: 'FBI agents pioneer criminal profiling of serial killers.',
                cast: 'Jonathan Groff, Holt McCallany, Anna Torv',
                genres: 'Crime, Drama, Thriller',
                tags: 'Psychological, True Crime'
            },
            {
                id: 28,
                title: 'Lucifer',
                image: 'https://image.tmdb.org/t/p/w500/ekZobS8isE6mA53RAiGDG93hBxL.jpg',
                trailer: 'CnXXmKl-0X0',
                year: 2015,
                rating: 'TV-14',
                duration: '6 Seasons',
                match: 89,
                description: 'The Devil runs an LA nightclub and consults for the LAPD.',
                cast: 'Tom Ellis, Lauren German, Kevin Alejandro',
                genres: 'Crime, Drama, Fantasy',
                tags: 'Supernatural, Witty'
            },
            {
                id: 29,
                title: 'The Boys',
                image: 'https://image.tmdb.org/t/p/w500/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg',
                trailer: 'PKIaJfR9d0w',
                year: 2019,
                rating: 'TV-MA',
                duration: '4 Seasons',
                match: 94,
                description: 'Vigilantes take down corrupt superheroes.',
                cast: 'Karl Urban, Antony Starr, Erin Moriarty',
                genres: 'Action, Comedy, Crime',
                tags: 'Superhero, Dark, Violent'
            },
            {
                id: 30,
                title: 'Dexter',
                image: 'https://m.media-amazon.com/images/M/MV5BMTQ3YmQ4YzMtOTkyZC00YmM5LThhZjEtM2E0MjFkNTc0OGJhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: 'tI7LCx3JWqc',
                year: 2006,
                rating: 'TV-14',
                duration: '9 Seasons',
                match: 92,
                description: 'A forensic analyst leads a double life as a serial killer.',
                cast: 'Michael C. Hall, Jennifer Carpenter, David Zayas',
                genres: 'Crime, Drama, Mystery',
                tags: 'Dark, Psychological'
            },
            {
                id: 31,
                title: 'The Office',
                image: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
                trailer: 'ffnM7C2KEEY',
                year: 2005,
                rating: 'TV-14',
                duration: '9 Seasons',
                match: 88,
                description: 'A mockumentary on office workers with ego clashes and tedium.',
                cast: 'Steve Carell, Rainn Wilson, Jenna Fischer',
                genres: 'Comedy',
                tags: 'Funny, Mockumentary'
            },
            {
                id: 32,
                title: 'Friends',
                image: 'https://m.media-amazon.com/images/M/MV5BOTU2YmM5ZjctOGVlMC00YTczLTljM2MtYjhlNGI5YWMyZjFkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: '2pJmKei2T3I',
                year: 1994,
                rating: 'TV-14',
                duration: '10 Seasons',
                match: 90,
                description: 'Six friends navigate life, love, and careers in New York City.',
                cast: 'Jennifer Aniston, Courteney Cox, Lisa Kudrow',
                genres: 'Comedy, Romance',
                tags: 'Sitcom, Iconic'
            }
        ],

        top10: [
            {
                id: 41,
                title: 'Avatar: The Last Airbender',
                image: 'https://image.tmdb.org/t/p/w500/9RQhVb3r3mCMqYVhLoCu4EvuipP.jpg',
                trailer: 'wVZUxnYo6_M',
                year: 2024,
                rating: 'TV-PG',
                duration: '1 Season',
                match: 93,
                description: 'The Avatar must master the elements to stop a ruthless enemy.',
                cast: 'Gordon Cormier, Kiawentiio, Ian Ousley',
                genres: 'Fantasy, Adventure, Action',
                tags: 'Epic, Family-Friendly',
                badge: 'top10',
                rank: 1
            },
            {
                id: 42,
                title: 'Griselda',
                image: 'https://m.media-amazon.com/images/M/MV5BMzdlNGU1MmItZDFhMi00YzQ1LTkyMDMtNWI4MDM5MDE3ZDg1XkEyXkFqcGc@._V1_.jpg',
                trailer: 'VtBKUBhXv1g',
                year: 2024,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 91,
                description: 'Griselda Blanco builds one of history\'s most profitable cartels.',
                cast: 'Sofía Vergara, Alberto Guerra, Martín Rodríguez',
                genres: 'Crime, Drama, Biography',
                tags: 'Gritty, Violent',
                badge: 'top10',
                rank: 2
            },
            {
                id: 43,
                title: 'The Gentlemen',
                image: 'https://m.media-amazon.com/images/M/MV5BMjE2ZjQ4ZGMtZjFhMi00NmI5LTliNjEtODczMWMxNjliZjgxXkEyXkFqcGc@._V1_QL75_UX190_CR0,0,190,281_.jpg',
                trailer: 'KAZrQ0z1Qqw',
                year: 2024,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 89,
                description: 'An inherited estate hides a massive weed empire.',
                cast: 'Theo James, Kaya Scodelario, Daniel Ings',
                genres: 'Crime, Comedy, Action',
                tags: 'Witty, Stylish',
                badge: 'top10',
                rank: 3
            },
            {
                id: 44,
                title: 'One Day',
                image: 'https://m.media-amazon.com/images/M/MV5BODVlNzI0MmYtYmE4Yi00ZTgxLThmY2ItNjE4YzY3NmQzZTNiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: 'gQTf_F5b5gc',
                year: 2024,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 92,
                description: 'Emma and Dexter\'s intertwined lives span decades after one night together.',
                cast: 'Ambika Mod, Leo Woodall, Eleanor Tomlinson',
                genres: 'Romance, Drama',
                tags: 'Emotional, Romantic',
                badge: 'top10',
                rank: 4
            },
            {
                id: 45,
                title: 'Fool Me Once',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP3N-orlA6WqNbjLlQTuz2S9qr1tGFntehig&s',
                trailer: 'w-iu67zg8dQ',
                year: 2024,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 88,
                description: 'A former soldier uncovers a web of deceit after seeing her murdered husband alive.',
                cast: 'Michelle Keegan, Richard Armitage, Adeel Akhtar',
                genres: 'Thriller, Mystery',
                tags: 'Suspenseful, Twisty',
                badge: 'top10',
                rank: 5
            },
            {
                id: 46,
                title: 'Obliterated',
                image: 'https://m.media-amazon.com/images/M/MV5BN2E5Mzg4MzctNzQ4NS00YzUwLWJkYTUtMmNlMzJiMGUzMzcwXkEyXkFqcGc@._V1_.jpg',
                trailer: 'rvegTb-xCrs',
                year: 2023,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 85,
                description: 'A special forces team must find a real bomb while drunk.',
                cast: 'Shelley Hennig, Nick Zano, Terrence Terrell',
                genres: 'Action, Comedy',
                tags: 'Funny, Action-Packed',
                badge: 'top10',
                rank: 6
            },
            {
                id: 47,
                title: '3 Body Problem',
                image: 'https://m.media-amazon.com/images/M/MV5BMDdkYWZiZWYtMzA0Yi00NzNlLThkODktY2Q3N2NjN2ExZmMwXkEyXkFqcGc@._V1_.jpg',
                trailer: 'BQJ_C4hqPfM',
                year: 2024,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 90,
                description: 'Five friends face cosmic mysteries as science itself unravels.',
                cast: 'Jovan Adepo, Eiza González, Jess Hong',
                genres: 'Sci-Fi, Mystery, Drama',
                tags: 'Mind-Bending, Epic',
                badge: 'top10',
                rank: 7
            },
            {
                id: 48,
                title: 'The Umbrella Academy',
                image: 'https://m.media-amazon.com/images/M/MV5BMDhiMTRmMjItZmNjOC00ZTYxLTg1MzYtZDYyZjNlMjhlMjI3XkEyXkFqcGc@._V1_.jpg',
                trailer: '0DAmWHxeoKw',
                year: 2019,
                rating: 'TV-14',
                duration: '4 Seasons',
                match: 94,
                description: 'A dysfunctional superhero family reunites to save the world.',
                cast: 'Elliot Page, Tom Hopper, David Castañeda',
                genres: 'Superhero, Sci-Fi, Comedy',
                tags: 'Quirky, Action-Packed',
                badge: 'top10',
                rank: 8
            },
            {
                id: 49,
                title: 'The Sandman',
                image: 'https://m.media-amazon.com/images/M/MV5BNjk0M2ZhZTQtZjQ0NC00ODA2LWFkN2ItMTA0ZTc0MjJjODg0XkEyXkFqcGc@._V1_QL75_UX190_CR0,0,190,281_.jpg',
                trailer: 'zxFm5lVG2l4',
                year: 2022,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 93,
                description: 'Morpheus escapes captivity and journeys to reclaim what was stolen.',
                cast: 'Tom Sturridge, Boyd Holbrook, Patton Oswalt',
                genres: 'Fantasy, Horror, Drama',
                tags: 'Dark, Imaginative',
                badge: 'top10',
                rank: 9
            },
            {
                id: 50,
                title: 'Beef',
                image: 'https://m.media-amazon.com/images/M/MV5BYzgxYzg0NmEtNzdhMy00NjFiLTg1MTQtM2EzMDRiOGEwZjI2XkEyXkFqcGc@._V1_.jpg',
                trailer: 'fP1omkuwUuU',
                year: 2023,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 96,
                description: 'A road rage incident spirals into an all-consuming feud.',
                cast: 'Steven Yeun, Ali Wong, Joseph Lee',
                genres: 'Drama, Comedy, Thriller',
                tags: 'Dark, Intense',
                badge: 'top10',
                rank: 10
            }
        ],

        originals: [
            {
                id: 51,
                title: '3 Body Problem',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVw_QXiOUDGCzyCrt_hW96Sl0ocrVN65adiQ&s',
                trailer: 'BQJ_C4hqPfM',
                year: 2024,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 90,
                description: 'Five friends face cosmic mysteries as science itself unravels.',
                cast: 'Jovan Adepo, Eiza González, Jess Hong',
                genres: 'Sci-Fi, Mystery, Drama',
                tags: 'Mind-Bending, Epic',
                badge: 'new'
            },
            {
                id: 52,
                title: 'The Umbrella Academy',
                image: 'https://m.media-amazon.com/images/M/MV5BMzlmMmIxODItYzBjNC00YjMwLWIwOTAtNzVlMTBlNTNkMjZjXkEyXkFqcGc@._V1_.jpg',
                trailer: '0DAmWHxeoKw',
                year: 2019,
                rating: 'TV-14',
                duration: '4 Seasons',
                match: 94,
                description: 'A dysfunctional superhero family reunites to save the world.',
                cast: 'Elliot Page, Tom Hopper, David Castañeda',
                genres: 'Superhero, Sci-Fi, Comedy',
                tags: 'Quirky, Action-Packed'
            },
            {
                id: 53,
                title: 'The Sandman',
                image: 'https://m.media-amazon.com/images/M/MV5BNjk0M2ZhZTQtZjQ0NC00ODA2LWFkN2ItMTA0ZTc0MjJjODg0XkEyXkFqcGc@._V1_.jpg',
                trailer: 'zxFm5lVG2l4',
                year: 2022,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 93,
                description: 'Morpheus escapes captivity and journeys to reclaim what was stolen.',
                cast: 'Tom Sturridge, Boyd Holbrook, Patton Oswalt',
                genres: 'Fantasy, Horror, Drama',
                tags: 'Dark, Imaginative'
            },
            {
                id: 54,
                title: 'Beef',
                image: 'https://m.media-amazon.com/images/M/MV5BYzgxYzg0NmEtNzdhMy00NjFiLTg1MTQtM2EzMDRiOGEwZjI2XkEyXkFqcGc@._V1_.jpg',
                trailer: 'fP1omkuwUuU',
                year: 2023,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 96,
                description: 'A road rage incident spirals into an all-consuming feud.',
                cast: 'Steven Yeun, Ali Wong, Joseph Lee',
                genres: 'Drama, Comedy, Thriller',
                tags: 'Dark, Intense'
            },
            {
                id: 55,
                title: 'Cobra Kai',
                image: 'https://image.tmdb.org/t/p/w500/6POBWybSBDBKjSs1VAQcnQC1qyt.jpg',
                trailer: 'xCwwaqt68Ic',
                year: 2018,
                rating: 'TV-14',
                duration: '6 Seasons',
                match: 91,
                description: 'Rivalries reignite when Johnny Lawrence reopens Cobra Kai.',
                cast: 'Ralph Macchio, William Zabka, Courtney Henggeler',
                genres: 'Action, Comedy, Drama',
                tags: 'Nostalgic, Uplifting'
            },
            {
                id: 56,
                title: 'Russian Doll',
                image: 'https://m.media-amazon.com/images/M/MV5BZWRlM2ExMDEtOWJhZS00YTM4LWE5MDAtMWQ1NWFkOWRiODQ5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: 'YHcKoAMGGvY',
                year: 2019,
                rating: 'TV-MA',
                duration: '2 Seasons',
                match: 89,
                description: 'A woman relives the same night repeatedly, dying each time.',
                cast: 'Natasha Lyonne, Charlie Barnett, Greta Lee',
                genres: 'Comedy, Sci-Fi, Mystery',
                tags: 'Quirky, Mind-Bending'
            },
            {
                id: 57,
                title: 'Lockwood & Co.',
                image: 'https://m.media-amazon.com/images/M/MV5BMzI1ODdjY2UtYzdkOC00Y2NjLWE2NzYtZjlmYWFkMGE1MDBmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: 'TfJHIJ6_FPE',
                year: 2023,
                rating: 'TV-PG',
                duration: '1 Season',
                match: 82,
                description: 'Psychic teens hunt ghosts in an alternate 1990s London.',
                cast: 'Ruby Stokes, Cameron Chapman, Ali Hadji-Heshmati',
                genres: 'Fantasy, Adventure, Mystery',
                tags: 'Supernatural, Team-Up'
            },
            {
                id: 58,
                title: 'The Diplomat',
                image: 'https://m.media-amazon.com/images/M/MV5BNjNhODY5OWEtZjMxNy00NzFhLWIzOTQtZTNmYjUwOGRiMzYwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: 'TfLvWu7llQA',
                year: 2023,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 90,
                description: 'Kate Wyler navigates international crises and political turmoil.',
                cast: 'Keri Russell, Rufus Sewell, Ali Ahn',
                genres: 'Thriller, Drama',
                tags: 'Political, Suspenseful'
            },
            {
                id: 59,
                title: 'Godless',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQux1Brfn5qR6qZ1YOuh4bLqMVgCPj2KcLO-w&s',
                trailer: 'd7K0I6F1j3w',
                year: 2017,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 86,
                description: 'A cowboy finds refuge in a town run entirely by women.',
                cast: 'Jeff Daniels, Michelle Dockery, Jack O\'Connell',
                genres: 'Western, Drama, Action',
                tags: 'Western, Unique'
            },
            {
                id: 60,
                title: 'Sweet Home',
                image: 'https://m.media-amazon.com/images/M/MV5BZDE0MTM5YjgtMzNhOS00NWE2LTkxN2EtMzg0NWRmODBmMDA5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: '_Gvp-cIlgQA',
                year: 2020,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 89,
                description: 'Residents fight monstrous creatures in a quarantined apartment complex.',
                cast: 'Song Kang, Lee Jin-uk, Lee Si-young',
                genres: 'Horror, Drama, Thriller',
                tags: 'Monster, Survival'
            }
        ],

        action: [
            {
                id: 61,
                title: 'Extraction',
                image: 'https://image.tmdb.org/t/p/w500/wlfDxbGEsW58vGhFljKkcR5IxDj.jpg',
                trailer: 'L6P3nI6VnlY',
                year: 2020,
                rating: 'R',
                duration: '1h 56m',
                match: 92,
                description: 'A mercenary must rescue a crime lord\'s kidnapped son in Bangladesh.',
                cast: 'Chris Hemsworth, Rudhraksh Jaiswal, Randeep Hooda',
                genres: 'Action, Thriller',
                tags: 'Violent, Intense'
            },
            {
                id: 62,
                title: 'The Gray Man',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXeSwA4IjGn-9t2BukXCqqeHIbtB9onmhuCg&s',
                trailer: 'BmllggGO4pM',
                year: 2022,
                rating: 'PG-13',
                duration: '2h 2m',
                match: 88,
                description: 'A CIA assassin is hunted by a psychopathic agent after uncovering secrets.',
                cast: 'Ryan Gosling, Chris Evans, Ana de Armas',
                genres: 'Action, Thriller',
                tags: 'Explosive, Spy Thriller'
            },
            {
                id: 63,
                title: 'Army of the Dead',
                image: 'https://m.media-amazon.com/images/M/MV5BNjc0MDFjZmQtMWMxZi00YzY4LWI5N2EtOGQwM2IzZjRkYmY1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: 'tI1JGPhYBS8',
                year: 2021,
                rating: 'R',
                duration: '2h 28m',
                match: 86,
                description: 'Mercenaries attempt a heist in zombie-infested Las Vegas.',
                cast: 'Dave Bautista, Ella Purnell, Omari Hardwick',
                genres: 'Action, Horror, Thriller',
                tags: 'Zombie, Heist'
            },
            {
                id: 64,
                title: 'The Old Guard',
                image: 'https://image.tmdb.org/t/p/w500/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg',
                trailer: 'aK-X2d0lJ_s',
                year: 2020,
                rating: 'R',
                duration: '2h 5m',
                match: 89,
                description: 'Immortal mercenaries fight to keep their identity secret.',
                cast: 'Charlize Theron, KiKi Layne, Matthias Schoenaerts',
                genres: 'Action, Fantasy',
                tags: 'Superhero, Violent'
            },
            {
                id: 65,
                title: 'Red Notice',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROY61TPvGGleF08WpjWPcbLqIPsYYF2mVhFg&s',
                trailer: 'Pj0wz7zu3Ms',
                year: 2021,
                rating: 'PG-13',
                duration: '1h 58m',
                match: 84,
                description: 'An Interpol agent pursues the world\'s most wanted art thief.',
                cast: 'Dwayne Johnson, Ryan Reynolds, Gal Gadot',
                genres: 'Action, Comedy, Thriller',
                tags: 'Fun, Heist'
            },
            {
                id: 66,
                title: '6 Underground',
                image: 'https://image.tmdb.org/t/p/w500/gCIB3DdK00DyfwosVGf7pnFFdK3.jpg',
                trailer: 'YLE85RDMkNQ',
                year: 2019,
                rating: 'R',
                duration: '2h 8m',
                match: 83,
                description: 'Six elite individuals fake their deaths to take down criminals.',
                cast: 'Ryan Reynolds, Mélanie Laurent, Manuel Garcia-Rulfo',
                genres: 'Action, Thriller',
                tags: 'Explosive, Fun'
            },
            {
                id: 67,
                title: 'The Adam Project',
                image: 'https://image.tmdb.org/t/p/w500/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg',
                trailer: 'I-8b8B7MfDw',
                year: 2022,
                rating: 'PG-13',
                duration: '1h 46m',
                match: 85,
                description: 'A time-traveling pilot teams up with his younger self to save the future.',
                cast: 'Ryan Reynolds, Mark Ruffalo, Jennifer Garner',
                genres: 'Action, Adventure, Sci-Fi',
                tags: 'Time Travel, Fun'
            },
            {
                id: 68,
                title: 'Gunpowder Milkshake',
                image: 'https://m.media-amazon.com/images/M/MV5BNmFhNTYwODItOTRhZi00MzJkLWIyNjAtYWRlMGVhODIyZmQ2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                trailer: 'PQ0EL04Fpy0',
                year: 2021,
                rating: 'R',
                duration: '1h 54m',
                match: 82,
                description: 'An assassin protects a daughter when her mother resurfaces.',
                cast: 'Karen Gillan, Lena Headey, Carla Gugino',
                genres: 'Action, Thriller',
                tags: 'Stylish, Violent'
            },
            {
                id: 69,
                title: 'Kate',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP8Jupps7haFI4Yi7303ZHkar3_vwVV3dTKw&s',
                trailer: '3mRqDQ72Qh8',
                year: 2021,
                rating: 'R',
                duration: '1h 46m',
                match: 80,
                description: 'A poisoned assassin races against time in Tokyo.',
                cast: 'Mary Elizabeth Winstead, Woody Harrelson, Miku Martineau',
                genres: 'Action, Thriller',
                tags: 'Intense, Stylish'
            },
            {
                id: 70,
                title: 'Bullet Train',
                image: 'https://image.tmdb.org/t/p/w500/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg',
                trailer: 'wtlIqn5v6Ow',
                year: 2022,
                rating: 'R',
                duration: '2h 6m',
                match: 86,
                description: 'Five assassins on a bullet train discover their missions are linked.',
                cast: 'Brad Pitt, Aaron Taylor-Johnson, Brian Tyree Henry',
                genres: 'Action, Thriller, Comedy',
                tags: 'Fun, Stylish'
            }
        ]
    }
};
