// ==========================================
// NETFLIX CLONE - CONFIGURATION
// ==========================================

const CONFIG = {
    // Netflix Content Data with Real Movie Information
    content: {
        trending: [
            {
                id: 1,
                title: 'Wednesday',
                image: 'https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
                trailer: 'Di310WS8zLk',
                year: 2022,
                rating: 'TV-14',
                duration: '1 Season',
                match: 97,
                description: 'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.',
                cast: 'Jenna Ortega, Gwendoline Christie, Riki Lindhome',
                genres: 'Comedy, Mystery, Supernatural',
                tags: 'Dark, Quirky, Teen',
                badge: 'new'
            },
            {
                id: 2,
                title: 'Squid Game',
                image: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
                trailer: 'oqxAJKy0ii4',
                year: 2021,
                rating: 'TV-MA',
                duration: '2 Seasons',
                match: 98,
                description: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits — with deadly high stakes.',
                cast: 'Lee Jung-jae, Park Hae-soo, Wi Ha-jun',
                genres: 'Thriller, Drama, Action',
                tags: 'Dark, Suspenseful, Violent'
            },
            {
                id: 3,
                title: 'The Witcher',
                image: 'https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg',
                trailer: 'ndl1W4ltcmg',
                year: 2019,
                rating: 'TV-MA',
                duration: '3 Seasons',
                match: 95,
                description: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
                cast: 'Henry Cavill, Anya Chalotra, Freya Allan',
                genres: 'Fantasy, Adventure, Action',
                tags: 'Dark, Epic, Violent'
            },
            {
                id: 4,
                title: 'Money Heist',
                image: 'https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg',
                trailer: '_InqKYnsjec',
                year: 2017,
                rating: 'TV-MA',
                duration: '5 Seasons',
                match: 96,
                description: 'Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan.',
                cast: 'Álvaro Morte, Úrsula Corberó, Itziar Ituño',
                genres: 'Crime, Thriller, Action',
                tags: 'Suspenseful, Exciting'
            },
            {
                id: 5,
                title: 'The Crown',
                image: 'https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg',
                trailer: 'JWtnJjn6ng0',
                year: 2016,
                rating: 'TV-MA',
                duration: '6 Seasons',
                match: 92,
                description: 'This drama follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the 20th century.',
                cast: 'Imelda Staunton, Jonathan Pryce, Lesley Manville',
                genres: 'Drama, Biography, History',
                tags: 'Period Piece, Royal'
            },
            {
                id: 6,
                title: 'Bridgerton',
                image: 'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p18301540_b_v13_ad.jpg',
                trailer: 'gpv7ayf_tyE',
                year: 2020,
                rating: 'TV-MA',
                duration: '3 Seasons',
                match: 94,
                description: 'The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society. Inspired by Julia Quinn\'s bestselling novels.',
                cast: 'Nicola Coughlan, Luke Newton, Phoebe Dynevor',
                genres: 'Romance, Drama, Period',
                tags: 'Romantic, Steamy'
            },
            {
                id: 31,
                title: 'Ginny & Georgia',
                image: 'https://resizing.flixster.com/8GH6cW8MeuzNITl2C44yGaKGZ9E=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p19614761_b_v13_aa.jpg',
                trailer: 'eC-tFJEkLVE',
                year: 2021,
                rating: 'TV-14',
                duration: '2 Seasons',
                match: 86,
                description: 'Free-spirited Georgia Miller and her daughter Ginny find themselves starting over in a picturesque New England town. But their past threatens everything.',
                cast: 'Antonia Gentry, Brianne Howey, Scott Speedman',
                genres: 'Drama, Comedy',
                tags: 'Teen, Coming-of-Age'
            },
            {
                id: 32,
                title: 'The Diplomat',
                image: 'https://resizing.flixster.com/m6-mJq18uC-8BqZPL9X6c6BXdIg=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vMTkyMGQzMGQtM2E3Yi00ZDQ4LWI5MTYtMzEwOTlhOGE4NTg5LmpwZw==',
                trailer: 'TfLvWu7llQA',
                year: 2023,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 90,
                description: 'In the midst of an international crisis, career diplomat Kate Wyler lands a high-profile job for which she is not suited, with tectonic implications for her marriage and political future.',
                cast: 'Keri Russell, Rufus Sewell, Ali Ahn',
                genres: 'Thriller, Drama',
                tags: 'Political, Suspenseful'
            },
            {
                id: 33,
                title: 'You',
                image: 'https://image.tmdb.org/t/p/w500/7bEYwjUvlJW7GerM8GYmqwl4oS3.jpg',
                trailer: 'bR_1xHgVAAQ',
                year: 2018,
                rating: 'TV-MA',
                duration: '4 Seasons',
                match: 93,
                description: 'A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is transfixed by.',
                cast: 'Penn Badgley, Elizabeth Lail, Ambyr Childers',
                genres: 'Thriller, Drama, Crime',
                tags: 'Dark, Psychological'
            },
            {
                id: 34,
                title: 'Firefly Lane',
                image: 'https://resizing.flixster.com/g1qRyVvJZ0V-xIqUBjKQfBqN4bU=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vNmEzZWM3YTktYTk3Yy00YTBmLTk0YzctNWUwYWZhYWY4ZDFlLmpwZw==',
                trailer: 'LppP2h0qxlI',
                year: 2021,
                rating: 'TV-14',
                duration: '2 Seasons',
                match: 87,
                description: 'For decades, childhood best friends Kate and Tully have weathered life\'s storms together — until a betrayal threatens to break them apart for good.',
                cast: 'Katherine Heigl, Sarah Chalke, Ali Skovbye',
                genres: 'Drama, Comedy',
                tags: 'Emotional, Nostalgic'
            },
            {
                id: 35,
                title: 'Sweet Magnolias',
                image: 'https://resizing.flixster.com/BwpTkKhNQi8J1pXk5vHKqNBMXXc=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vYTI4OTYxZjUtM2RmYS00ZjI3LWI0NTMtOTJmNGE0NTU5M2M0LmpwZw==',
                trailer: '7K-fXdMxIJQ',
                year: 2020,
                rating: 'TV-14',
                duration: '3 Seasons',
                match: 85,
                description: 'Lifelong friends lift each other up as they juggle relationships, family and careers in the small, Southern town of Serenity.',
                cast: 'Heather Headley, JoAnna Garcia Swisher, Brooke Elliott',
                genres: 'Drama',
                tags: 'Friendship, Southern'
            },
            {
                id: 36,
                title: 'Chilling Adventures of Sabrina',
                image: 'https://image.tmdb.org/t/p/w500/yxMpoHO0CXP5o9gB7IfsciilQS4.jpg',
                trailer: 'LgHnXpzKKVw',
                year: 2018,
                rating: 'TV-14',
                duration: '4 Seasons',
                match: 88,
                description: 'Magic and mischief collide as half-human, half-witch Sabrina navigates between two worlds: mortal teen life and her family\'s legacy, the Church of Night.',
                cast: 'Kiernan Shipka, Ross Lynch, Lucy Davis',
                genres: 'Fantasy, Horror, Drama',
                tags: 'Dark, Witches'
            }
        ],
        
        popular: [
            {
                id: 7,
                title: 'Stranger Things',
                image: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
                trailer: 'OsqUh1p1Ock',
                year: 2016,
                rating: 'TV-14',
                duration: '4 Seasons',
                match: 98,
                description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
                cast: 'Millie Bobby Brown, Finn Wolfhard, Winona Ryder',
                genres: 'Sci-Fi, Horror, Drama',
                tags: 'Nostalgic, Scary, 80s'
            },
            {
                id: 8,
                title: 'Breaking Bad',
                image: 'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
                trailer: 'HhesaQXLuRY',
                year: 2008,
                rating: 'TV-MA',
                duration: '5 Seasons',
                match: 99,
                description: 'A high school chemistry teacher dying of cancer teams with a former student to secure his family\'s future by manufacturing and selling crystal meth.',
                cast: 'Bryan Cranston, Aaron Paul, Anna Gunn',
                genres: 'Crime, Drama, Thriller',
                tags: 'Dark, Gritty, Intense'
            },
            {
                id: 9,
                title: 'Dark',
                image: 'https://image.tmdb.org/t/p/w500/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
                trailer: 'rrwycJ08PSA',
                year: 2017,
                rating: 'TV-MA',
                duration: '3 Seasons',
                match: 96,
                description: 'A family saga with a supernatural twist, set in a German town, where the disappearance of two young children exposes the relationships among four families.',
                cast: 'Louis Hofmann, Karoline Eichhorn, Lisa Vicari',
                genres: 'Thriller, Sci-Fi, Mystery',
                tags: 'Mind-Bending, Dark'
            },
            {
                id: 10,
                title: 'Peaky Blinders',
                image: 'https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg',
                trailer: 'oVzVdvGIC7U',
                year: 2013,
                rating: 'TV-MA',
                duration: '6 Seasons',
                match: 95,
                description: 'A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps.',
                cast: 'Cillian Murphy, Paul Anderson, Sophie Rundle',
                genres: 'Crime, Drama, Period',
                tags: 'Gritty, Stylish, Violent'
            },
            {
                id: 11,
                title: 'Ozark',
                image: 'https://resizing.flixster.com/8a5Yee5h_qK2LhJXy-IWPUKuGSI=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vNGI2NDQ3NTItNzgzZi00NTY4LWExMGUtYmI4ZTg3MzhmNWU3LmpwZw==',
                trailer: '5hAXVqrljbs',
                year: 2017,
                rating: 'TV-MA',
                duration: '4 Seasons',
                match: 94,
                description: 'A financial adviser drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.',
                cast: 'Jason Bateman, Laura Linney, Sofia Hublitz',
                genres: 'Crime, Drama, Thriller',
                tags: 'Dark, Suspenseful'
            },
            {
                id: 12,
                title: 'The Queen\'s Gambit',
                image: 'https://image.tmdb.org/t/p/w500/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg',
                trailer: 'CDrieqwSdgI',
                year: 2020,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 97,
                description: 'In a 1950s orphanage, a young girl reveals an astonishing talent for chess and begins an unlikely journey to stardom while grappling with addiction.',
                cast: 'Anya Taylor-Joy, Chloe Pirrie, Bill Camp',
                genres: 'Drama, Period',
                tags: 'Inspiring, Period Piece'
            },
            {
                id: 37,
                title: 'Mindhunter',
                image: 'https://resizing.flixster.com/vhEwLDWwD4Ss6xSPFa0a_hVAZco=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vNzI5NDJhYmItNmMzNS00MzJiLWE0MTktZDFjYTY3M2FhNjgwLmpwZw==',
                trailer: 'aLEVRYFxQhc',
                year: 2017,
                rating: 'TV-MA',
                duration: '2 Seasons',
                match: 91,
                description: 'In the late 1970s, FBI agents Holden Ford and Bill Tench begin studying serial killers\' psychology, pioneering modern criminal profiling.',
                cast: 'Jonathan Groff, Holt McCallany, Anna Torv',
                genres: 'Crime, Drama, Thriller',
                tags: 'Psychological, True Crime'
            },
            {
                id: 38,
                title: 'Lucifer',
                image: 'https://image.tmdb.org/t/p/w500/ekZobS8isE6mA53RAiGDG93hBxL.jpg',
                trailer: 'CnXXmKl-0X0',
                year: 2015,
                rating: 'TV-14',
                duration: '6 Seasons',
                match: 89,
                description: 'Lucifer, the Devil himself, leaves Hell to spend time on Earth as the owner of an upscale nightclub in Los Angeles.',
                cast: 'Tom Ellis, Lauren German, Kevin Alejandro',
                genres: 'Crime, Drama, Fantasy',
                tags: 'Supernatural, Witty'
            },
            {
                id: 39,
                title: 'The Boys',
                image: 'https://image.tmdb.org/t/p/w500/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg',
                trailer: 'PKIaJfR9d0w',
                year: 2019,
                rating: 'TV-MA',
                duration: '4 Seasons',
                match: 94,
                description: 'When a group of vigilantes set out to take down corrupt superheroes, they uncover a conspiracy that reaches the highest levels of power.',
                cast: 'Karl Urban, Antony Starr, Dominique McElligott',
                genres: 'Action, Comedy, Crime',
                tags: 'Superhero, Dark, Violent'
            },
            {
                id: 40,
                title: 'Dexter',
                image: 'https://resizing.flixster.com/8ksxUiME6aqpLBbHO-YaS5ykUxs=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vZDUzYzQzNGUtMDY2ZS00YzcwLWI1M2QtYzJhN2EwZThhNzEwLmpwZw==',
                trailer: 'tI7LCx3JWqc',
                year: 2006,
                rating: 'TV-14',
                duration: '9 Seasons',
                match: 92,
                description: 'A forensic blood spatter analyst for the Miami Metro Police Department, Dexter Morgan leads a double life as a serial killer.',
                cast: 'Michael C. Hall, Jennifer Carpenter, David Zayas',
                genres: 'Crime, Drama, Mystery',
                tags: 'Dark, Psychological'
            },
            {
                id: 41,
                title: 'The Office',
                image: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
                trailer: 'ffnM7C2KEEY',
                year: 2005,
                rating: 'TV-14',
                duration: '9 Seasons',
                match: 88,
                description: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
                cast: 'Steve Carell, Rainn Wilson, Jenna Fischer',
                genres: 'Comedy',
                tags: 'Funny, Mockumentary'
            },
            {
                id: 42,
                title: 'Friends',
                image: 'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p183156_b_v13_be.jpg',
                trailer: '2pJmKei2T3I',
                year: 1994,
                rating: 'TV-14',
                duration: '10 Seasons',
                match: 90,
                description: 'Six friends navigate life, love, career, and everything in between in New York City.',
                cast: 'Jennifer Aniston, Courteney Cox, Lisa Kudrow',
                genres: 'Comedy, Romance',
                tags: 'Sitcom, Iconic'
            }
        ],
        
        top10: [
            {
                id: 13,
                title: 'Avatar: The Last Airbender',
                image: 'https://image.tmdb.org/t/p/w500/9RQhVb3r3mCMqYVhLoCu4EvuipP.jpg',
                trailer: 'wVZUxnYo6_M',
                year: 2024,
                rating: 'TV-PG',
                duration: '1 Season',
                match: 93,
                description: 'A young boy known as the Avatar must master the four elemental powers to save a world at war — and fight a ruthless enemy bent on stopping him.',
                cast: 'Gordon Cormier, Kiawentiio, Ian Ousley',
                genres: 'Fantasy, Adventure, Action',
                tags: 'Epic, Family-Friendly',
                badge: 'top10',
                rank: 1
            },
            {
                id: 14,
                title: 'Griselda',
                image: 'https://resizing.flixster.com/ovWCgMthzO9v5KwXzjXD5QSn-g0=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vZTcwNDUxNjItMzk2MS00YmI2LWI3YWEtYzBlNzY5Y2FkMDM0LmpwZw==',
                trailer: 'VtBKUBhXv1g',
                year: 2024,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 91,
                description: 'Chronicles the life of Griselda Blanco, who created one of the most profitable cartels in history. A devoted mother, Blanco\'s lethal blend of charm and unsuspecting savagery helped her expertly navigate between family and business.',
                cast: 'Sofía Vergara, Alberto Guerra, Martín Rodríguez',
                genres: 'Crime, Drama, Biography',
                tags: 'Gritty, Violent',
                badge: 'top10',
                rank: 2
            },
            {
                id: 15,
                title: 'The Gentlemen',
                image: 'https://resizing.flixster.com/W0TyiB8lWXuVsC89w7G1ljm56Ko=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vOTUzZDU5MzgtODM0Yy00NzJhLTk3ODItMzU2NzU2NjM5Y2E2LmpwZw==',
                trailer: 'KAZrQ0z1Qqw',
                year: 2024,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 89,
                description: 'When aristocratic Eddie inherits the family estate, he discovers that it\'s home to an enormous weed empire — and its proprietors aren\'t going anywhere.',
                cast: 'Theo James, Kaya Scodelario, Daniel Ings',
                genres: 'Crime, Comedy, Action',
                tags: 'Witty, Stylish',
                badge: 'top10',
                rank: 3
            },
            {
                id: 16,
                title: 'One Day',
                image: 'https://resizing.flixster.com/fFtjPGFsHVEOXZGq2JQXZ4_JAwM=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vZjlmYzU4ODktOGY5MS00YjA5LWIyODgtMzU2ZDFlM2E4YmJhLmpwZw==',
                trailer: 'gQTf_F5b5gc',
                year: 2024,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 92,
                description: 'After spending graduation night together, Emma and Dexter go their separate ways — but their lives remain intertwined.',
                cast: 'Ambika Mod, Leo Woodall, Eleanor Tomlinson',
                genres: 'Romance, Drama',
                tags: 'Emotional, Romantic',
                badge: 'top10',
                rank: 4
            },
            {
                id: 17,
                title: 'Fool Me Once',
                image: 'https://resizing.flixster.com/CKgGfJ8R0SLBIOpGGdGdnTyQPME=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vYzU5NzY3NjgtN2JlYy00YmU0LWE5MWQtMzEzZTA1YzMxOWU3LmpwZw==',
                trailer: 'w-iu67zg8dQ',
                year: 2024,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 88,
                description: 'When a former soldier discovers her murdered husband is alive, she becomes entangled in a web of deceit.',
                cast: 'Michelle Keegan, Richard Armitage, Adeel Akhtar',
                genres: 'Thriller, Mystery',
                tags: 'Suspenseful, Twisty',
                badge: 'top10',
                rank: 5
            },
            {
                id: 18,
                title: 'Obliterated',
                image: 'https://resizing.flixster.com/rnLF5WjULlDyYvjDEe2a_zD8V1g=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vNzJjYjA0MTctYjYwMi00Y2VhLWJhNTgtNDEwNTYyYmNlZDM5LmpwZw==',
                trailer: 'rvegTb-xCrs',
                year: 2023,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 85,
                description: 'An elite special forces team celebrates a successful mission, only to discover the bomb they defused was a fake. Now drunk, they must find the real bomb.',
                cast: 'Shelley Hennig, Nick Zano, Terrence Terrell',
                genres: 'Action, Comedy',
                tags: 'Funny, Action-Packed',
                badge: 'top10',
                rank: 6
            },
            {
                image: 'https://image.tmdb.org/t/p/w500/ps2Bw2Mg8bVKe0GKGR3K7Rvwqy7.jpg',
                trailer: '5jrfmkKGXDc',
                year: 2023,
                rating: 'TV-14',
                duration: '1 Season',
                match: 87,
                description: 'A low-level FBI employee gets caught in a dangerous game after he answers a call from an untraceable number.',
                cast: 'Gabriel Basso, Hong Chau, Luciane Buchanan',
                genres: 'Thriller, Drama',
                tags: 'Suspenseful, Fast-Paced',
                badge: 'top10',
                rank: 7
            },
            {
                image: 'https://image.tmdb.org/t/p/w500/bFYBHBvdpL0YoZKM2T9v5PwMvqo.jpg',
                trailer: 'Oj9YtYJnVcE',
                year: 2023,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 86,
                description: 'A newly graduated CIA officer gets embroiled in an international crisis in this breezy action comedy series.',
                cast: 'Noah Centineo, Tess Haubrich, Colton Haynes',
                genres: 'Action, Comedy, Thriller',
                tags: 'Fun, Spy Thriller',
                badge: 'top10',
                rank: 8
            },
            {
                image: 'https://image.tmdb.org/t/p/w500/3fBv5eSLuLREz7iRvPqfLj2BzEH.jpg',
                trailer: 'C_Lxzqkwn0A',
                year: 2024,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 84,
                description: 'A cynical woman and a devout man fall in love and must navigate their wildly different worlds.',
                cast: 'Kristen Bell, Adam Brody, Justin Long',
                genres: 'Romance, Comedy, Drama',
                tags: 'Romantic Comedy, Witty',
                badge: 'top10',
                rank: 9
            },
            {
                image: 'https://image.tmdb.org/t/p/w500/3MN5RPKf6zDXPFx4iVxHCNGVZT5.jpg',
                trailer: 'hAC0qNwmF1w',
                year: 2024,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 88,
                description: 'During a snowstorm, a drifter and a young woman seek refuge in a cabin, and a strange friendship develops.',
                cast: 'Taron Egerton, Sofia Carson, Cary Elwes',
                genres: 'Action, Thriller, Comedy',
                tags: 'Holiday, Action',
                badge: 'top10',
                rank: 10
            }
        ],
        
        originals: [
            {
                id: 19,
                title: '3 Body Problem',
                image: 'https://resizing.flixster.com/g5jQo8TxJ6Wv3vE-VY-cO1KkS4U=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vNTBiZGY0MzUtNGQxZC00YmJhLTk3MGQtMjFjZGY1MzU5NTM0LmpwZw==',
                trailer: 'BQJ_C4hqPfM',
                year: 2024,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 90,
                description: 'Across continents and decades, five brilliant friends make earth-shattering discoveries as the laws of science unravel.',
                cast: 'Jovan Adepo, Eiza González, Jess Hong',
                genres: 'Sci-Fi, Mystery, Drama',
                tags: 'Mind-Bending, Epic',
                badge: 'new'
            },
            {
                id: 20,
                title: 'The Umbrella Academy',
                image: 'https://resizing.flixster.com/yN2I7Zsy1KrELG7OyGmwcPXZUx4=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vNGU4YWI4NWYtZDgwNC00MDY3LWI3NjktOGIxYzExZGVmMWM2LmpwZw==',
                trailer: '0DAmWHxeoKw',
                year: 2019,
                rating: 'TV-14',
                duration: '4 Seasons',
                match: 94,
                description: 'A dysfunctional family of superheroes comes together to solve the mystery of their father\'s death, the threat of the apocalypse and more.',
                cast: 'Elliot Page, Tom Hopper, David Castañeda',
                genres: 'Superhero, Sci-Fi, Comedy',
                tags: 'Quirky, Action-Packed'
            },
            {
                id: 21,
                title: 'The Sandman',
                image: 'https://image.tmdb.org/t/p/w500/q54qEgagGOYCq5D1903eBVMNkbo.jpg',
                trailer: 'zxFm5lVG2l4',
                year: 2022,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 93,
                description: 'After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him.',
                cast: 'Tom Sturridge, Boyd Holbrook, Patton Oswalt',
                genres: 'Fantasy, Horror, Drama',
                tags: 'Dark, Imaginative'
            },
            {
                id: 22,
                title: 'Beef',
                image: 'https://resizing.flixster.com/T-Z3QJHF8J1XBNnR8L10MgVX26U=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vN2Y5M2Y3ZDktMjUzZS00MTUzLTgyZTctNjYxMjYzNDg3NDczLmpwZw==',
                trailer: 'fP1omkuwUuU',
                year: 2023,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 96,
                description: 'A road rage incident between two strangers spirals into an all-consuming obsession, upending their lives.',
                cast: 'Steven Yeun, Ali Wong, Joseph Lee',
                genres: 'Drama, Comedy, Thriller',
                tags: 'Dark, Intense'
            },
            {
                id: 23,
                title: 'Cobra Kai',
                image: 'https://image.tmdb.org/t/p/w500/6POBWybSBDBKjSs1VAQcnQC1qyt.jpg',
                trailer: 'xCwwaqt68Ic',
                year: 2018,
                rating: 'TV-14',
                duration: '6 Seasons',
                match: 91,
                description: 'Decades after the tournament, Johnny Lawrence seeks redemption by reopening Cobra Kai, reigniting his rivalry with Daniel LaRusso.',
                cast: 'Ralph Macchio, William Zabka, Courtney Henggeler',
                genres: 'Action, Comedy, Drama',
                tags: 'Nostalgic, Uplifting'
            },
            {
                id: 24,
                title: 'Russian Doll',
                image: 'https://resizing.flixster.com/rlT9_hJ6xXtd8I8fDVQswmAE0ZU=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vNjUwNWVhZjUtOGE1Yy00ZmViLTllMzUtNTE4ZWYzOWRhZTE5LmpwZw==',
                trailer: 'YHcKoAMGGvY',
                year: 2019,
                rating: 'TV-MA',
                duration: '2 Seasons',
                match: 89,
                description: 'A woman gets caught in a mysterious loop, repeatedly attending the same party and dying at the end of the night, only to awaken the next day unharmed.',
                cast: 'Natasha Lyonne, Charlie Barnett, Greta Lee',
                genres: 'Comedy, Sci-Fi, Mystery',
                tags: 'Quirky, Mind-Bending'
            },
            {
                image: 'https://image.tmdb.org/t/p/w500/oGYKOdANiKMEHvGWPdBRhqHkVt.jpg',
                trailer: 'TfJHIJ6_FPE',
                year: 2023,
                rating: 'TV-PG',
                duration: '1 Season',
                match: 82,
                description: 'Three young psychic detectives hunt supernatural mysteries in an alternate London of the 1990s where ghosts are real.',
                cast: 'Jack Bandeira, Olivia Colman, Thaddea Graham',
                genres: 'Fantasy, Adventure, Mystery',
                tags: 'Supernatural, Fantasy'
            },
            {
                image: 'https://image.tmdb.org/t/p/w500/6zyaHvWJnNv0kWI9SYIPpNpLvpd.jpg',
                trailer: 'OqIDFcmC3T4',
                year: 2023,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 95,
                description: 'U.S. ambassador Kate Wyler finds herself in the middle of an international crisis and thrust into the spotlight.',
                cast: 'Keri Russell, Rufus Sewell, Ali Ahn',
                genres: 'Thriller, Drama',
                tags: 'Political, Intense'
            },
            {
                image: 'https://image.tmdb.org/t/p/w500/3LdqAzXe2jmNKPXKIaHYaYZmW7W.jpg',
                trailer: 'd7K0I6F1j3w',
                year: 2017,
                rating: 'TV-MA',
                duration: 'Limited Series',
                match: 86,
                description: 'A cowboy arrives in a town run exclusively by women after fleeing a gang of outlaws.',
                cast: 'Jeff Daniels, Michelle Dockery, Michelle Bonev',
                genres: 'Western, Drama, Action',
                tags: 'Western, Unique'
            },
            {
                image: 'https://image.tmdb.org/t/p/w500/fyVmNMPd7GGhCz0hjRH9p75HzP2.jpg',
                trailer: '_Gvp-cIlgQA',
                year: 2020,
                rating: 'TV-MA',
                duration: '1 Season',
                match: 89,
                description: 'As a grisly virus spreads through an apartment complex, a reclusive man must decide whether to save his neighbors or survive alone.',
                cast: 'Lee Jin-uk, Lee Si-young, Park Gyu-young',
                genres: 'Horror, Drama, Thriller',
                tags: 'Zombie, Dark'
            }
        ],
        
        action: [
            {
                id: 25,
                title: 'Extraction',
                image: 'https://image.tmdb.org/t/p/w500/wlfDxbGEsW58vGhFljKkcR5IxDj.jpg',
                trailer: 'L6P3nI6VnlY',
                year: 2020,
                rating: 'R',
                duration: '1h 56m',
                match: 92,
                description: 'A hardened mercenary\'s mission becomes a soul-searching race to survive when he\'s sent into Bangladesh to rescue a drug lord\'s kidnapped son.',
                cast: 'Chris Hemsworth, Rudhraksh Jaiswal, Randeep Hooda',
                genres: 'Action, Thriller',
                tags: 'Violent, Intense'
            },
            {
                id: 26,
                title: 'The Gray Man',
                image: 'https://resizing.flixster.com/yFkSR3vgE5Y3hYYzNY9T4n6CQ0A=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2Q2NTdmYzgzLTU4N2UtNGEyOC1iZDcwLWEzYzI0MzJhNzBlZi5qcGc=',
                trailer: 'BmllggGO4pM',
                year: 2022,
                rating: 'PG-13',
                duration: '2h 2m',
                match: 88,
                description: 'When a shadowy CIA agent uncovers damning agency secrets, he\'s hunted across the globe by a sociopathic rogue operative who\'s put a bounty on his head.',
                cast: 'Ryan Gosling, Chris Evans, Ana de Armas',
                genres: 'Action, Thriller',
                tags: 'Explosive, Spy Thriller'
            },
            {
                id: 27,
                title: 'Army of the Dead',
                image: 'https://resizing.flixster.com/dS9K5rZGN6TcLv3RNXK9Y_v2DSI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2YxMjIzMDdjLTQ5YTgtNDRhMy1hZDljLTk3YzJlNjM2ODkxYS5qcGc=',
                trailer: 'tI1JGPhYBS8',
                year: 2021,
                rating: 'R',
                duration: '2h 28m',
                match: 86,
                description: 'Following a zombie outbreak in Las Vegas, a group of mercenaries takes the ultimate gamble, venturing into the quarantine zone to pull off the greatest heist ever.',
                cast: 'Dave Bautista, Ella Purnell, Omari Hardwick',
                genres: 'Action, Horror, Thriller',
                tags: 'Zombie, Violent'
            },
            {
                id: 28,
                title: 'The Old Guard',
                image: 'https://image.tmdb.org/t/p/w500/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg',
                trailer: 'aK-X2d0lJ_s',
                year: 2020,
                rating: 'R',
                duration: '2h 5m',
                match: 89,
                description: 'A covert team of immortal mercenaries are suddenly exposed and must now fight to keep their identity a secret.',
                cast: 'Charlize Theron, KiKi Layne, Matthias Schoenaerts',
                genres: 'Action, Fantasy',
                tags: 'Superhero, Violent'
            },
            {
                id: 29,
                title: 'Red Notice',
                image: 'https://resizing.flixster.com/7gykGZpx0sqj3M9Jjo5EYi-2EZY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzk5ZWY4YTNmLWI4NjktNGQ3Zi05MWY4LTMyYzE5N2Q2MzBjNi5qcGc=',
                trailer: 'Pj0wz7zu3Ms',
                year: 2021,
                rating: 'PG-13',
                duration: '1h 58m',
                match: 84,
                description: 'An Interpol agent tracks the world\'s most wanted art thief.',
                cast: 'Dwayne Johnson, Ryan Reynolds, Gal Gadot',
                genres: 'Action, Comedy, Thriller',
                tags: 'Fun, Heist'
            },
            {
                id: 30,
                title: '6 Underground',
                image: 'https://resizing.flixster.com/FJqgqAEsn7dDshUPOzG6_rMOJWA=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzU1NDZmZjIxLTkyMmItNGIzNS1hZDg3LTExYjc5M2JiZGU4Ni5qcGc=',
                trailer: 'YLE85RDMkNQ',
                year: 2019,
                rating: 'R',
                duration: '2h 8m',
                match: 83,
                description: 'Six individuals from all around the globe, each the very best at what they do, have been chosen not only for their skill, but for a unique desire to delete their pasts.',
                cast: 'Ryan Reynolds, Mélanie Laurent, Manuel Garcia-Rulfo',
                genres: 'Action, Thriller',
                tags: 'Explosive, Fun'
            },
            {
                id: 51,
                title: 'The Adam Project',
                image: 'https://image.tmdb.org/t/p/w500/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg',
                trailer: 'I-8b8B7MfDw',
                year: 2022,
                rating: 'PG-13',
                duration: '1h 46m',
                match: 85,
                description: 'A man from the future works with his younger self to uncover the truth about his past and change the future.',
                cast: 'Ryan Reynolds, Mark Ruffalo, Jennifer Garner',
                genres: 'Action, Adventure, Sci-Fi',
                tags: 'Time Travel, Fun'
            },
            {
                id: 52,
                title: 'Gunpowder Milkshake',
                image: 'https://resizing.flixster.com/B9vqXHEPAUpOLhZCVtRKuBP6YEk=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzY4NjE4MTg1LTQwZjQtNDMzYi1hZDEwLWYzNGFiNDRkYmIzMS5qcGc=',
                trailer: 'PQ0EL04Fpy0',
                year: 2021,
                rating: 'R',
                duration: '1h 54m',
                match: 82,
                description: 'When her estranged mother reemerges, an assassin protects the young daughter she\'s kept hidden.',
                cast: 'Karen Gillan, Lena Headey, Carla Gugino',
                genres: 'Action, Thriller',
                tags: 'Stylish, Violent'
            },
            {
                id: 53,
                title: 'Kate',
                image: 'https://resizing.flixster.com/DYzGC3iOHVnAf3kxrS_nI7cXjuc=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzkyYmJiZTViLTU1ZDgtNDQyMS05NzIwLTNhMjNjOGU3YjgwMi5qcGc=',
                trailer: '3mRqDQ72Qh8',
                year: 2021,
                rating: 'R',
                duration: '1h 46m',
                match: 80,
                description: 'A talented assassin wakes up in Tokyo with poison in her veins, forcing her to face her past as she uncovers a conspiracy.',
                cast: 'Mary Elizabeth Winstead, Woody Harrelson, Miku Martineau',
                genres: 'Action, Thriller',
                tags: 'Intense, Stylish'
            },
            {
                id: 54,
                title: 'Bullet Train',
                image: 'https://image.tmdb.org/t/p/w500/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg',
                trailer: 'wtlIqn5v6Ow',
                year: 2022,
                rating: 'R',
                duration: '2h 6m',
                match: 86,
                description: 'Five assassins aboard a fast-moving bullet train find out their missions have something in common and unwittingly become connected.',
                cast: 'Brad Pitt, Aaron Taylor-Johnson, Brian Tyree Henry',
                genres: 'Action, Thriller, Comedy',
                tags: 'Fun, Stylish'
            }
        ]
    }
};
