// Quick script to generate replacements
const imageMap = {
  'Wednesday': 'https://m.media-amazon.com/images/M/MV5BYWEyMjZhYjItODk0Yy00ZWQwLTk3NTAtNDAzYmVlMjBhMzM1XkEyXkFqcGc@._V1_.jpg',
  'Squid Game': 'https://m.media-amazon.com/images/M/MV5BOGQ5OTk3NDctYTAxOC00ZWQwLTk5MTItMDAyNzEzODI2ODA5XkEyXkFqcGc@._V1_.jpg',
  'The Witcher': 'https://m.media-amazon.com/images/M/MV5BMjMyNjkzMzEtNmQ2Yy00NjZlLWE5ZTAtN2M1ZTJjNWMwMDA0XkEyXkFqcGc@._V1_.jpg',
  'Money Heist': 'https://m.media-amazon.com/images/M/MV5BOTk0NDEwOWEtODg5Ny00MTk5LWFhZjUtMGY4NDY3Y2VjZjI3XkEyXkFqcGc@._V1_.jpg',
  'The Crown': 'https://m.media-amazon.com/images/M/MV5BZjQyNjcxNmUtMjcwYi00ZWEzLThjOTAtZTMyZTAwODEyZTA1XkEyXkFqcGc@._V1_.jpg',
  'Bridgerton': 'https://m.media-amazon.com/images/M/MV5BYWEyMDI5MzAtZjAxOC00YTcxLWJlY2UtZGY4YzFkNGE2MDAzXkEyXkFqcGc@._V1_.jpg',
  'Ginny & Georgia': 'https://m.media-amazon.com/images/M/MV5BMjAwMzQwNjAtY2U2YS00ZmI2LTkyODgtYWQ0ZGEyMTk0YjIxXkEyXkFqcGc@._V1_.jpg',
  'The Diplomat': 'https://m.media-amazon.com/images/M/MV5BYzljZmJkNDItNjBiMy00ZWIxLTk1NzMtNzMxZGNkNjkzMTcwXkEyXkFqcGc@._V1_.jpg',
  'You': 'https://m.media-amazon.com/images/M/MV5BZGZhMDI3N2ItMjNjYy00MDk3LWFkOTctMjNjZWQyZGNkMDhlXkEyXkFqcGc@._V1_.jpg',
  'Firefly Lane': 'https://m.media-amazon.com/images/M/MV5BN2VjYTMwMWEtODg1Yi00NjA3LTk5MzItOWY4YjhkYjBjOTE2XkEyXkFqcGc@._V1_.jpg',
  'Sweet Magnolias': 'https://m.media-amazon.com/images/M/MV5BZDJhNTczZGMtMzM3Yi00MzI1LWE1ZDAtYWQzZTc1MjM0ZjA4XkEyXkFqcGc@._V1_.jpg',
  'Chilling Adventures of Sabrina': 'https://m.media-amazon.com/images/M/MV5BMjM3Mjg1MzA2MF5BMl5BanBnXkFtZTgwNzE4Mjc4NzM@._V1_.jpg',
  'Stranger Things': 'https://m.media-amazon.com/images/M/MV5BMjk1NTU3NzA4Nl5BMl5BanBnXkFtZTgwODc0NzM2NzM@._V1_.jpg',
  'Breaking Bad': 'https://m.media-amazon.com/images/M/MV5BMjMyNjkzMzEtNmQ2Yy00NjZlLWE5ZTAtN2M1ZTJjNWMwMDA0XkEyXkFqcGc@._V1_.jpg',
  'Dark': 'https://m.media-amazon.com/images/M/MV5BNTc4YTI5MWItMDAxNy00ZGI1LWE2ZDAtNGE1OTI5YmQ1NzMwXkEyXkFqcGc@._V1_.jpg',
  'Peaky Blinders': 'https://m.media-amazon.com/images/M/MV5BZTMyYzFmNTYtZjAxOC00YWEyLTk1ZDAtMzdjYTA0YTI0YzhhXkEyXkFqcGc@._V1_.jpg',
  'Ozark': 'https://m.media-amazon.com/images/M/MV5BMjM1NzU0OGEtODcwOS00OTcwLWI0MjktNTAwMzY4YzdhNDU1XkEyXkFqcGc@._V1_.jpg',
  'The Queen\'s Gambit': 'https://m.media-amazon.com/images/M/MV5BMmY3OGUwMjgtN2I5Ny00ZTBiLTg4MzktYzU2ZGNjZWI3ZDQ0XkEyXkFqcGc@._V1_.jpg',
  'Mindhunter': 'https://m.media-amazon.com/images/M/MV5BMjQ2OTljM2ItNzA1YS00ZTA2LWE5NTAtODk4ZjBiNzAzODA5XkEyXkFqcGc@._V1_.jpg',
  'Lucifer': 'https://m.media-amazon.com/images/M/MV5BOTQzODkzNzYxNl5BMl5BanBnXkFtZTgwOTAxMjE4NzM@._V1_.jpg',
  'The Boys': 'https://m.media-amazon.com/images/M/MV5BMjAxOTcyMDAtODg5YS00YTdjLTkxYTgtOWMxODdjOWRkOThhXkEyXkFqcGc@._V1_.jpg',
  'Dexter': 'https://m.media-amazon.com/images/M/MV5BMjExMzA4NzI5Nl5BMl5BanBnXkFtZTcwOTQwMjc3OQ@@._V1_.jpg',
  'The Office': 'https://m.media-amazon.com/images/M/MV5BMDNhMjAxOC00ZTBjLThhODAtZjZkYTI1OGE2OWJjXkEyXkFqcGc@._V1_.jpg',
  'Friends': 'https://m.media-amazon.com/images/M/MV5BMDNhMjAxOC00ZTBjLThhODAtZjZkYTI1OGE2OWJjXkEyXkFqcGc@._V1_.jpg',
  'Avatar: The Last Airbender': 'https://m.media-amazon.com/images/M/MV5BNWNjYTcxMGItNTU5Yy00ZjAzLWI5ZDItN2U0MzU1M2Y3OTAwXkEyXkFqcGc@._V1_.jpg',
  'Griselda': 'https://m.media-amazon.com/images/M/MV5BMzk3YTUzMjgtNDZmOS00NDQ2LWJiYTQtNzZmZGE0ZjQxZTczXkEyXkFqcGc@._V1_.jpg',
  'The Gentlemen': 'https://m.media-amazon.com/images/M/MV5BMDlmZGQwOWUtMDg5Ny00MzZmLThjMmUtYjBkNGU2ZmU2MjJkXkEyXkFqcGc@._V1_.jpg',
  'One Day': 'https://m.media-amazon.com/images/M/MV5BYzI5YTQzNTYtNzQ1OS00ZDFkLTk0ZGEtNzJiYjEyNmZkMDg1XkEyXkFqcGc@._V1_.jpg',
  'Fool Me Once': 'https://m.media-amazon.com/images/M/MV5BZGU5MjMyZTYtNzEzNS00OGI3LWI4YmUtOGQ2YWE5NzE2ZGJlXkEyXkFqcGc@._V1_.jpg',
  'Obliterated': 'https://m.media-amazon.com/images/M/MV5BMjI5YTYwOWQtZmY2Yy00NTQ3LWJjZmMtY2M0ZjhlMDQ0NDcxXkEyXkFqcGc@._V1_.jpg',
  '3 Body Problem': 'https://m.media-amazon.com/images/M/MV5BNzU5YjgzYzctODEyNi00YWQ1LWFlYzQtZTI3ZjE5MDAxZWJhXkEyXkFqcGc@._V1_.jpg',
  'The Umbrella Academy': 'https://m.media-amazon.com/images/M/MV5BYzg5OGM3OTItNzEyMy00ZmI0LTkwYTUtMWM0YTZlMzMzMWYyXkEyXkFqcGc@._V1_.jpg',
  'The Sandman': 'https://m.media-amazon.com/images/M/MV5BYjhkN2Q5ZDEtMmY0NS00ODczLWJjMTUtNDk2MDI5YTc0ZjJjXkEyXkFqcGc@._V1_.jpg',
  'Beef': 'https://m.media-amazon.com/images/M/MV5BMjI0ZTMyNjItMzQ5YS00ZjYxLWI5YmYtYTkyNDc2MzI5NzJhXkEyXkFqcGc@._V1_.jpg',
  'Cobra Kai': 'https://m.media-amazon.com/images/M/MV5BMjg2NzljMzAtYzE4Ny00MzAwLWE3MDItOWFmYTg5NTQyZGJjXkEyXkFqcGc@._V1_.jpg',
  'Russian Doll': 'https://m.media-amazon.com/images/M/MV5BMzY5MTNkNjMtZWQ0OC00YzAwLWJmZTAtNjMwMWEwY2ExNDlmXkEyXkFqcGc@._V1_.jpg',
  'Extraction': 'https://m.media-amazon.com/images/M/MV5BMjU5NTZjMDMtN2I3Ni00NjA5LWJhN2MtODAwY2M5OTdlYTJhXkEyXkFqcGc@._V1_.jpg',
  'The Gray Man': 'https://m.media-amazon.com/images/M/MV5BZjZkM2ZkZmEtNzc2Yi00NzE4LWI0NDQtYzU1NDEwYmJkYTI4XkEyXkFqcGc@._V1_.jpg',
  'Army of the Dead': 'https://m.media-amazon.com/images/M/MV5BMjAxZDkwNGUtZWQxNS00ODMwLWE1MjItYWEwMGRmZjUzMjQ1XkEyXkFqcGc@._V1_.jpg',
  'The Old Guard': 'https://m.media-amazon.com/images/M/MV5BMThlMzAxOTAtMDk5Ni00MWI5LTg0OTItZThjNGNlYzEyNTc5XkEyXkFqcGc@._V1_.jpg',
  'Red Notice': 'https://m.media-amazon.com/images/M/MV5BYjI1Mjc3MGUtMWUzNS00MzYyLTg5ZjYtOGYxODBmZjZiMjc2XkEyXkFqcGc@._V1_.jpg',
  '6 Underground': 'https://m.media-amazon.com/images/M/MV5BZjJhYzhjNDMtNGY2Mi00YzAxLTkwZWItNTAwMWIyM2ZhOTI3XkEyXkFqcGc@._V1_.jpg',
  'The Adam Project': 'https://m.media-amazon.com/images/M/MV5BYzljZmJkNDItNjBiMy00ZWIxLTk1NzMtNzMxZGNkNjkzMTcwXkEyXkFqcGc@._V1_.jpg',
  'Gunpowder Milkshake': 'https://m.media-amazon.com/images/M/MV5BMDViOGFkMmItMDQwYS00OTZhLWE5MjctMDY5MzAxYjg0YTg1XkEyXkFqcGc@._V1_.jpg',
  'Kate': 'https://m.media-amazon.com/images/M/MV5BMzJhNDk4YTctOWY5NS00MGUwLWI4NjYtODk0YjJkYTZlZjhhXkEyXkFqcGc@._V1_.jpg',
  'Bullet Train': 'https://m.media-amazon.com/images/M/MV5BYjI2ZGJkN2YtMDkxZi00ZDljLWI0ZjAtNDMzY2I3MWY0NzUzXkEyXkFqcGc@._V1_.jpg'
};

console.log(imageMap);
